version: '3'

services:
  api:
    build: app
    restart: always
    expose:
      - 8000
    networks:
      - proxy-api-network
  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - proxy-api-network

networks:
  proxy-api-network: