FROM python:3.10.6-slim
WORKDIR /app
EXPOSE 8000
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .

CMD [ "uvicorn", "main:app" ,"--reload", "--host", "0.0.0.0", "--port", "8000" ]
